### ISSUE TITLE
szamla respone returns undefined

### ISSUE THREAD

**Issue by laszloerno** [ewngs/szamlazz.js#43]
Hi,

i'm using your latest version and created a test application as since 2 days the invoice response is not working in my productive app. After contacting Szamlazz.hu they told me that nothing has been change on their side.
The response of getInvoiceData is undefined.

```
import { Client } from 'szamlazz.js';

const szamlazas = async () => {
  const szamlazzClient = new Client({
    authToken: szamlazzHuToken,
    eInvoice: false, // create e-invoice. optional, default: false
    requestInvoiceDownload: false, // downloads the issued pdf invoice. optional, default: false
    downloadedInvoiceCount: 1, // optional, default: 1
    responseVersion: 1, // optional, default: 1
  });

  szamlazzClient
    .getInvoiceData({
      invoiceId: 'SCR-2023-121', // invoice number
      pdf: false, // downloads the pdf invoice. optional, default: false
    })
    .then((adat) => {
      console.log('szamla', adat);
    });
};

export default { szamlazas };
```

maybe  i do something wrong please varify that the response is working for you, if yes then please share some hint where i'm wrong :) with my code.

thanks

**Comment by ert78gb** [comment]
Something should change on the szamlazz.hu side, if everything worked fine earlier.

I use the lib only generate invoice, so I don't know what is the expected output of the `getInvoiceData` method.

I debug your example and with this setup. It returns with `undefined` for me too.
The problem is in the `_sendRequest` method returns with [AxiosResponse](https://github.com/axios/axios/tree/v0.x#response-schema) in the [line](https://github.com/ewngs/szamlazz.js/blob/53e6988417e6a8d86433ea9c97de609009b7c947/lib/Client.js#L50). `AxoisResponse.data` contains the response. So it should be parsed to get back the `szamla` data.

If szamlazz.hu did not change anything and you also did not upgraded the library then this code does not work for a while.
I am opening a PR that fix this use case but I don't know who will confirm it fix cover every case

**Comment by laszloerno** [comment]
thanks for the prompt reply, yes now it works fine !

**Comment by ert78gb** [comment]
sry. I don't understand. Now after the szamlazz.hu outage everything works without the PR #44?

**Comment by laszloerno** [comment]
no after i implemented your fix it solved the issue.

**Comment by ert78gb** [comment]
ok, then we merge the PR and we will deploy a new version

**Comment by laszloerno** [comment]
thanks again :)
